"""initial interview schema

Revision ID: 975f61b782e0
Revises:
Create Date: 2026-08-05 20:57:06.834484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '975f61b782e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'PREPARING', 'READY', 'INTRODUCTION', 'ASKING', 'LISTENING', 'EVALUATING', 'FOLLOW_UP', 'NEXT_QUESTION', 'COMPLETING', 'COMPLETED', 'PAUSED', 'ABORTED', 'FAILED', name='ck_interviews_state_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_interviews_version'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('interview_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'PREPARING', 'READY', 'INTRODUCTION', 'ASKING', 'LISTENING', 'EVALUATING', 'FOLLOW_UP', 'NEXT_QUESTION', 'COMPLETING', 'COMPLETED', 'PAUSED', 'ABORTED', 'FAILED', name='ck_interview_sessions_state_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resume_state', sa.Enum('CREATED', 'PREPARING', 'READY', 'INTRODUCTION', 'ASKING', 'LISTENING', 'EVALUATING', 'FOLLOW_UP', 'NEXT_QUESTION', 'COMPLETING', 'COMPLETED', 'PAUSED', 'ABORTED', 'FAILED', name='ck_interview_sessions_resume_state_values', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('current_question_id', sa.String(length=255), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resume_state IS NULL OR resume_state IN ('INTRODUCTION', 'ASKING', 'LISTENING', 'EVALUATING', 'FOLLOW_UP', 'NEXT_QUESTION', 'COMPLETING')", name='ck_interview_sessions_resume_state'),
    sa.CheckConstraint('current_question_index >= 0', name='ck_interview_sessions_question_index'),
    sa.CheckConstraint('follow_up_count >= 0', name='ck_interview_sessions_follow_up_count'),
    sa.CheckConstraint('version >= 1', name='ck_interview_sessions_version'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_sessions_interview_id', 'interview_sessions', ['interview_id', 'created_at'], unique=False)
    op.create_table('interview_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'CONNECTED', 'DISCONNECTED', 'FAILED', name='ck_interview_attempts_state_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    op.create_index('idx_interview_attempts_session_id', 'interview_attempts', ['session_id', 'created_at'], unique=False)
    op.create_table('interview_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('state_before', sa.Enum('CREATED', 'PREPARING', 'READY', 'INTRODUCTION', 'ASKING', 'LISTENING', 'EVALUATING', 'FOLLOW_UP', 'NEXT_QUESTION', 'COMPLETING', 'COMPLETED', 'PAUSED', 'ABORTED', 'FAILED', name='ck_interview_events_state_before_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('state_after', sa.Enum('CREATED', 'PREPARING', 'READY', 'INTRODUCTION', 'ASKING', 'LISTENING', 'EVALUATING', 'FOLLOW_UP', 'NEXT_QUESTION', 'COMPLETING', 'COMPLETED', 'PAUSED', 'ABORTED', 'FAILED', name='ck_interview_events_state_after_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('version_before', sa.Integer(), nullable=False),
    sa.Column('version_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_after >= version_before', name='ck_interview_events_version_order'),
    sa.CheckConstraint('version_before >= 1', name='ck_interview_events_version_before'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_events_session_id', 'interview_events', ['session_id', 'version_after', 'created_at'], unique=False)
    op.create_table('interview_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='ck_interview_reports_state_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_interview_reports_state', 'interview_reports', ['state', 'updated_at'], unique=False)
    op.create_table('interview_answers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('answer_number', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('RECEIVED', 'EVALUATING', 'EVALUATED', 'FAILED', name='ck_interview_answers_state_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_event_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('answer_number >= 1', name='ck_interview_answers_number'),
    sa.CheckConstraint('length(trim(transcript)) > 0', name='ck_interview_answers_transcript'),
    sa.ForeignKeyConstraint(['attempt_id'], ['interview_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['interview_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', 'answer_number', name='uq_interview_answers_session_question_number'),
    sa.UniqueConstraint('source_event_id')
    )
    op.create_index('idx_interview_answers_session_question', 'interview_answers', ['session_id', 'question_id', 'answer_number'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('answer_id', sa.String(length=64), nullable=False),
    sa.Column('rubric_version', sa.Integer(), nullable=False),
    sa.Column('evaluation_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rubric_version >= 1', name='ck_answer_evaluations_rubric_version'),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_evaluations')
    op.drop_index('idx_interview_answers_session_question', table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index('idx_interview_reports_state', table_name='interview_reports')
    op.drop_table('interview_reports')
    op.drop_index('idx_interview_events_session_id', table_name='interview_events')
    op.drop_table('interview_events')
    op.drop_index('idx_interview_attempts_session_id', table_name='interview_attempts')
    op.drop_table('interview_attempts')
    op.drop_index('idx_interview_sessions_interview_id', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_table('interviews')
    # ### end Alembic commands ###
